# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# don't "logout" (close window) with CTRL+D
setopt IGNORE_EOF

# shorten escape timeout
KEYTIMEOUT=1

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# aliases
alias vzf='nvim $(fzf)'
if [[ $OSTYPE == darwin* ]]; then
  # MacOS
  alias ls='ls -G'
fi

# git
alias g='git'
alias ga='git add'
alias gb='git branch'
alias gbc='git branch | cat'
alias gc='git commit -v'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gf='git fetch'
alias gl='git log'
alias gsh='git show'
alias gst='git status'

# nnn file manager
alias nnn='nnn-nerd-static -eoR'

# something is incorrectly setting LS_COLORS, which makes `ls` output look bad
# export LS_COLORS="di=34:ln=35:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
export LS_COLORS=""

# asdf version manager
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit
compinit
# source the main script
. $ASDF_DIR/asdf.sh

# starship prompt
eval "$(starship init zsh)"
